In [13]:
import os
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
import pickle

In [2]:
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')
gender = pd.read_csv('gender_submission.csv')

In [3]:
train[["Pclass", "Sex", "SibSp", "Parch"]]

Pclass     Sex  SibSp  Parch
0         3    male      1      0
1         1  female      1      0
2         3  female      0      0
3         1  female      1      0
4         3    male      0      0
..      ...     ...    ...    ...
886       2    male      0      0
887       1  female      0      0
888       3  female      1      2
889       1    male      0      0
890       3    male      0      0

[891 rows x 4 columns]

In [4]:
train["Pclass"].unique()

array([3, 1, 2], dtype=int64)

In [9]:
train["Sex"].unique()

array(['male', 'female'], dtype=object)

In [10]:
train["SibSp"].unique()

array([1, 0, 3, 4, 2, 5, 8], dtype=int64)

In [11]:
train["Parch"].unique()

array([0, 1, 2, 5, 3, 4, 6], dtype=int64)

In [6]:
gender

PassengerId  Survived
0            892         0
1            893         1
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [7]:
women = train.loc[train.Sex == 'female']['Survived']
# rate_women = sum(women)/len(women)

# print("% of women who survived:", rate_women)
sum(women)
len(women)

314

In [12]:
y = train["Survived"]

features = ["Pclass", "Sex", "SibSp", "Parch"]
X = pd.get_dummies(train[features])
X_test = pd.get_dummies(test[features])

model = RandomForestClassifier(n_estimators=100, max_depth=5, random_state=1)
model.fit(X, y)
predictions = model.predict(X)

output = pd.DataFrame({'PassengerId': train.PassengerId, 'Survived': predictions})
output.to_csv('my_submission.csv', index=False)
print("Your submission was successfully saved!")

Your submission was successfully saved!


In [14]:
pickle.dump(model, open('model.pkl','wb'))

In [19]:
X

Pclass  SibSp  Parch  Sex_female  Sex_male
0         3      1      0           0         1
1         1      1      0           1         0
2         3      0      0           1         0
3         1      1      0           1         0
4         3      0      0           0         1
..      ...    ...    ...         ...       ...
886       2      0      0           0         1
887       1      0      0           1         0
888       3      1      2           1         0
889       1      0      0           0         1
890       3      0      0           0         1

[891 rows x 5 columns]

In [20]:
# Loading model to compare the results
model = pickle.load( open('model.pkl','rb'))
print(model.predict([[3,1,0,0,1]]))

[0]
